# Use official Nginx image
FROM nginx:alpine

# Copy indem.html to the default nginx HTML directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Nginx runs by default on port 80

