apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    release: monitoring  
spec:
  selector:
    matchLabels:
      app: my-nginx
  endpoints:
    - port: metrics
      interval: 10s
